---
- hosts: node1
  become: true
  remote_user: root
  tasks:
    - block:
      - get_url:
        url: http://rhgls/access
        register: accessible
      rescue:
        - copy:
            content: "I have no access "
            dest: /var/www/html/access.html
      

    - name: creating page
      copy:
        content: "I am accessible"
        dest: /var/www/html/access.html
      when: accessible | success
