--- 
- hosts: all
  become: true
  remote_user: root
  tasks:
    - name: create the private directory
      file:
        path: /var/www/html/private
        state: directory
        mode: 0755
    - name: download htaccess-custome
      get_url:
        url: http://rhgls/htaccess-cusome
        dest: /var/www/html/private/.htaccess
        mode: 0755

    - name: download htaccess-htpass
      get_url:
        url: http://rhgls/htpasswd
        dest: /var/www/html/private/.htpasswd
        mode: 0755

    - name: replace AllowOverride None to AllowOverride AuthConfig
      replace:
        dest: /etc/httpd/conf/httpd.conf
        regexp: "AllowOverride None"
        replace: "AllowOverride AuthConfig"
    
    - name: creating index.html page
      copy: 
        content: "This node {{ item }} is private"
        dest: /etc/www/html/private/index.html
      with_items:
        - node1
        - node2
        - node3
        - node4
