---
- hosts: servera
  become: true
  remote_user: devops
  vars_files:
    - secrete.yml
  tasks:
    - name: creating users from secrete.yml
      user: 
        name: "{{ item.name }}"
        password: "{{ item.pw | password_hash('sha512') }}"
        #here password_hash is funtion takes input as encrypted pass form secrete.yml file
      with_items: "{{ newusers }}"

